var texto = "CAMA P/COLCHAO 138 BARRETO SIENA CAFE	"



const palavrasChave146 = [
  "AIRFRYER",
  "AIR FRYER",
  "AIR CLIMBER",
  "APARADOR DE GRAMA",
  "ASSADOR",
  "BATED",
  "BAT 4VEL",
  "BAT 8VEL",
  "BAT PLAN",
  "BATED.",
  "BATEDEIRA",
  "BIC",
  "BIC",
  "BICICLETA",
  "BICI",
  "CAFET.",
  "CAFETEIRA",
  "NESPRESSO",
  "TRES CORACOES VERSA",
  "CAIXA ACUSTICA",
  "CARRINHO",
  "CELULAR",
  "CILINDRO",
  "CHURRASQUEIRA",
  "MULTIMIX",
  "COMPRESSOR",
  "CORTADOR DE GRAMA",
  "CORTADOR",
  "ELETROSERRA",
  "ESMERILHADEIRA",
  "CLOUD WALKER",
  "DIGITAL IB=VERTER",
  "EASY WAY GENIS",
  "EST ELET",
  "EST ELETRONICA",
  "ESTEIRA",
  "GENIS",
  "EXTRATOR",
  "EXTRATORA",
  "PHILIPS FERRO PERFECTCARE",
  "FRIT ELET",
  "FRITADEIRA",
  "FURADEIRA",
  "INVERSOR DE SOLDA",
  "INVERSOR DIG",
  "INVERSOR SOLDA",
  "LAMINADOR",
  "LIQUIDIFICADOR",
  "LIQ",
  "LIQUID",
  "LIQUIDIFCADOR",
  "OSTER NEW REVERSE",
  "SOPEIRA",
  "LIXADEIRA",
  "MAKITA",
  "MAQUINA DE COSTURA",
  "M.COST.",
  "MAQ COSTURA",
  "MAQ COST",
  "MAQUINA DE COSTURA",
  "MA QUINA COSTURA",
  "COSTURA",
  "MARTELETE",
  "MICRO RETIFICA",
  "KIT MULTIUSO",
  "MOTOBOMBA",
  "ROCAD.CID 51,7CC CID520",
  "MOTOCOMPRESSOR",
  "MOTOESMERIL",
  "MOTOSERRA",
  "CENTRIFUGA DE FRUTAS",
  "KIT CREATIVE GOURMET",
  "MULTIPRO.",
  "MULTIPROC",
  "MULTIPROCESSADOR",
  "NUTRI NINJA",
  "PROCESSADOR",
  "MULTICHEF",
  "SHARK NUTRI",
  "PAN ELET",
  "PLAINA ELETRICA",
  "PANIFICADORA",
  "PARAFUSADEIRA",
  "PARAFU FURAD",
  "PISTOLA PINTURA",
  "PISTOLA PULVERIZADORA",
  "POLITRIZ",
  "PRAN GAMA",
  "ROCADEIRA",
  "SECADOR",
  "SERRA CIRCULAR",
  "SERRA",
  "SOVADEIRA",
  "TABLET",
  "SOPRADOR",
  "HOME THEATER",
  
];


  const palavrasChave1 = [
    "ES.",
    "ROUPEIRO",
    "CONJUGADO",
    "TP RT 140X75 ALMIRO",
    "ARMARIO",
    "COZINHA",
    "ESTOFADO",
    "CAD",
    "MOVEIS",
    "SALA",
    "POL",
    "ORTOBOM",
    "GR",
    "BANQUETA",
    "HOME",
    "CADEIRA",
    "PENTEADEIRA",
    "TORRE",
    "G.R.",
    "ARMA",
    "ARM",
    "G.ROU",
    "MODULO",
    "CONJ",
    "EST.",
    "COLCHÃO",
    "COL",
    "CRIADO",
    "CAB",
    "CABEC",
    "DORMITORIO",
    "CRIST",
    "KITS PAN",
    "BALCO",
    "BALCCO",
    "BALC",
    "ESCRIVAN",
    "CONJ.",
    "ESTOF",
    "S0FA",
    "SOFA",
    "Sofa",
    "BOX",
    "COMODA",
    "KIT COZ",
    "MOD",
    "CJ EST",
    "RACK",
    "COLCHAO",
    "POLTRONA",
    "POLT",
    "PAINEL",
    "MESA",
    "BASE",
    "ADEGA",
    "PAN",
    "COZ",
    "BALCAO",
    "ESTANTE",
    "CANTO",
    "CAMA",
    "EST HOME",
    "ROUP",
    "GAB PIA",
    "KIT 5P",
    "KIT 6P",
    "BERCO",
    "EST",
    "SOFÁ",
    "CAD.",
    "G RP",
    "PANELEIRO",
    "COLC",
    "NICHO",
    "CASAL",
    "KIT",
    "ARMÁRIO",
    "BANCADA",
    "BAL",
    "FRUTEIRA",
    "PANEL",
    "FRU",
    "COZ.",
    "PANEL.",
    "AEREO",
    "FRUT",
    "BUFFET",
    "COZIN",
    "CRISTALEIRA",
    "KITDEMOBILE",
    "3RM",
    "LOFT",
    "BALC.",
    "BALCÃO",
    "MULTIUSO",
    "GAVETEIRO",
    "BOX",
    "BELICHE",
    "CONJUG",
    "CABECEIRA",
    "TRELICHE",
    "TRILICHE",
    "POLTR",

  ];



const contemPalavraChave146 = palavrasChave146.some(palavra => typeof texto === 'string' && texto.includes(palavra));

// Verifica se o texto contém uma das palavras-chave existentes para 1
const contemPalavraChave1 = palavrasChave1.some(palavra => {
  const regex = new RegExp(`\\b${palavra}\\b`, 'i');
  return typeof texto === 'string' && regex.test(texto);
});

// Define o valor da empresa com base nas condições
let resultado;
if (contemPalavraChave146) {
    resultado = 146;
} else if (contemPalavraChave1) {
    resultado = 1;
} else {
    resultado = 64;
}

console.log(resultado);
 